import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const TRANSLATIONS = {
  English: {
    // Nav / Sidebar
    nav_dashboard:    'Dashboard',
    nav_upload:       'Upload ECG Image',
    nav_settings:     'Settings',
    nav_about:        'About Us',
    nav_support:      'Help & Support',
    nav_profile:      'My Profile',
    nav_logout:       'Logout',
    nav_new_scan:     '+ New ECG Scan',
    nav_ecg_digitizer:'ECG Digitizer',
    // Dashboard
    dash_welcome:     'Welcome back',
    dash_summary:     "Here's a summary of your ECG digitization activity",
    dash_total_scans: 'Total Scans',
    dash_avg_snr:     'Average SNR',
    dash_avg_time:    'Avg Process Time',
    dash_avg_dice:    'Avg Dice Score',
    dash_recent:      'Recent Scans',
    dash_new_scan:    '+ New Scan',
    dash_record_id:   'Record ID',
    dash_date:        'Date',
    dash_leads:       'Leads',
    dash_snr:         'SNR',
    dash_duration:    'Duration',
    dash_status:      'Status',
    dash_success:     'Success',
    dash_cta_title:   'Ready to analyze a new ECG?',
    dash_cta_sub:     'Upload a paper scan and get digitized signals in under a minute',
    dash_cta_btn:     'Start Analysis →',
    dash_no_scans:    'No scans yet.',
    dash_upload_first:'Upload your first ECG →',
    dash_refresh:     'Refresh',
    // Upload
    upload_title:     '12-Lead ECG Analyzer',
    upload_sub:       'Upload a paper or digital ECG · AI digitizes all 13 leads',
    upload_select:    'Select ECG Image',
    upload_choose:    'Click to choose ECG image…',
    upload_analyze:   'Analyze ECG',
    upload_processing:'Processing…',
    upload_error:     'Server connection failed',
    upload_empty_h:   'No ECG analyzed yet',
    upload_empty_p:   'Upload an ECG image above to get started',
    upload_leads:     'Leads Detected',
    upload_samples:   'Samples (Lead II)',
    upload_duration:  'Duration (est.)',
    upload_snr:       'SNR Score',
    upload_record:    'Record ID',
    tab_medical:      '📋 Medical ECG',
    tab_leads:        '📈 All Leads',
    tab_overlay:      '🔬 13-Lead Overlay',
    tab_original:     '🖼 Original Image',
    // Profile
    profile_title:    'My Profile',
    profile_sub:      'View and manage your personal information',
    profile_edit:     'Edit Profile',
    profile_save:     'Save Changes',
    profile_cancel:   'Cancel',
    profile_complete: 'Profile Complete',
    profile_total:    'Total Scans',
    profile_snr:      'Avg SNR',
    profile_upload_photo: 'Upload Photo',
    profile_change_photo: 'Change Photo',
    profile_remove:   'Remove',
    profile_info:     'Personal Information',
    profile_info_sub: 'Your basic profile details',
    profile_updated:  'Profile updated successfully!',
    profile_fullname: 'Full Name',
    profile_email:    'Email Address',
    profile_age:      'Age',
    profile_gender:   'Gender',
    profile_phone:    'Phone',
    profile_readonly: 'Read only',
    profile_account:  'Account',
    profile_chg_pwd:  'Change Password',
    profile_chg_sub:  'Update your login password',
    profile_update:   'Update',
    profile_del_acct: 'Delete Account',
    profile_del_sub:  'Permanently remove your account and all data',
    profile_delete:   'Delete',
    // Settings
    settings_title:   'Settings',
    settings_sub:     'Manage your preferences and account settings',
    settings_appear:  'Appearance',
    settings_appear_sub: 'Choose how the app looks across all pages',
    settings_lang:    'Language & Region',
    settings_lang_sub:'Select your preferred display language',
    settings_language:'Language',
    settings_timezone:'Time Zone',
    settings_save:    'Save Changes',
    settings_saved:   'Saved!',
    settings_cur_theme:'Current Theme',
    settings_acct:    'Account Settings',
    settings_manage:  'Manage',
    theme_light:      'Light',
    theme_dark:       'Dark',
    theme_neon:       'Neon',
    theme_light_desc: 'Clean white interface',
    theme_dark_desc:  'Easy on the eyes',
    theme_neon_desc:  'High-contrast vibrant',
    // Help
    help_title:       'Help & Support',
    help_sub:         'Find answers or get in touch with our team',
    help_docs:        'Documentation',
    help_docs_sub:    'Guides & API docs',
    help_chat:        'Live Chat',
    help_chat_sub:    'Mon–Fri, 9am–6pm',
    help_email:       'Email Us',
    help_faq:         'Frequently Asked Questions',
    help_search:      'Search questions…',
    help_contact:     'Send us a Message',
    help_contact_sub: "We'll get back to you within 1 business day",
    help_send:        'Send Message',
    help_name:        'Name',
    help_email_lbl:   'Email',
    help_subject:     'Subject',
    help_message:     'Message',
    help_sent:        "Message sent! We'll be in touch.",
    // About
    about_leadership: 'Leadership',
    about_team:       'Our Team',
    about_papers:     'Research Papers',
    about_mission:    'Our Mission',
    about_tech:       'Our Technology',
    about_open_pdf:   'Open PDF',
    // Logout
    logout_title:     'Log out?',
    logout_msg:       "You'll be returned to the login screen. Any unsaved work will be lost.",
    logout_cancel:    'Cancel',
    logout_confirm:   'Yes, Logout',
  },

  Hindi: {
    nav_dashboard:    'डैशबोर्ड',
    nav_upload:       'ECG छवि अपलोड करें',
    nav_settings:     'सेटिंग्स',
    nav_about:        'हमारे बारे में',
    nav_support:      'सहायता',
    nav_profile:      'मेरी प्रोफ़ाइल',
    nav_logout:       'लॉग आउट',
    nav_new_scan:     '+ नई ECG स्कैन',
    nav_ecg_digitizer:'ECG डिजिटाइज़र',
    dash_welcome:     'वापस स्वागत है',
    dash_summary:     'आपकी ECG डिजिटाइज़ेशन गतिविधि का सारांश',
    dash_total_scans: 'कुल स्कैन',
    dash_avg_snr:     'औसत SNR',
    dash_avg_time:    'औसत प्रसंस्करण समय',
    dash_avg_dice:    'औसत Dice स्कोर',
    dash_recent:      'हाल की स्कैन',
    dash_new_scan:    '+ नई स्कैन',
    dash_record_id:   'रिकॉर्ड ID',
    dash_date:        'दिनांक',
    dash_leads:       'लीड्स',
    dash_snr:         'SNR',
    dash_duration:    'अवधि',
    dash_status:      'स्थिति',
    dash_success:     'सफल',
    dash_cta_title:   'नई ECG विश्लेषण के लिए तैयार?',
    dash_cta_sub:     'पेपर स्कैन अपलोड करें और एक मिनट में डिजिटल सिग्नल पाएं',
    dash_cta_btn:     'विश्लेषण शुरू करें →',
    dash_no_scans:    'अभी तक कोई स्कैन नहीं।',
    dash_upload_first:'अपना पहला ECG अपलोड करें →',
    dash_refresh:     'रीफ्रेश',
    upload_title:     '12-लीड ECG विश्लेषक',
    upload_sub:       'पेपर या डिजिटल ECG अपलोड करें · AI सभी 13 लीड डिजिटाइज़ करता है',
    upload_select:    'ECG छवि चुनें',
    upload_choose:    'ECG छवि चुनने के लिए क्लिक करें…',
    upload_analyze:   'ECG विश्लेषण करें',
    upload_processing:'प्रसंस्करण…',
    upload_error:     'सर्वर कनेक्शन विफल',
    upload_empty_h:   'अभी तक कोई ECG विश्लेषण नहीं',
    upload_empty_p:   'शुरू करने के लिए ऊपर एक ECG छवि अपलोड करें',
    upload_leads:     'पहचाने गए लीड',
    upload_samples:   'नमूने (लीड II)',
    upload_duration:  'अवधि (अनुमानित)',
    upload_snr:       'SNR स्कोर',
    upload_record:    'रिकॉर्ड ID',
    tab_medical:      '📋 मेडिकल ECG',
    tab_leads:        '📈 सभी लीड',
    tab_overlay:      '🔬 13-लीड ओवरले',
    tab_original:     '🖼 मूल छवि',
    profile_title:    'मेरी प्रोफ़ाइल',
    profile_sub:      'अपनी व्यक्तिगत जानकारी देखें और प्रबंधित करें',
    profile_edit:     'प्रोफ़ाइल संपादित करें',
    profile_save:     'बदलाव सहेजें',
    profile_cancel:   'रद्द करें',
    profile_complete: 'प्रोफ़ाइल पूर्ण',
    profile_total:    'कुल स्कैन',
    profile_snr:      'औसत SNR',
    profile_upload_photo: 'फ़ोटो अपलोड करें',
    profile_change_photo: 'फ़ोटो बदलें',
    profile_remove:   'हटाएं',
    profile_info:     'व्यक्तिगत जानकारी',
    profile_info_sub: 'आपकी बुनियादी प्रोफ़ाइल जानकारी',
    profile_updated:  'प्रोफ़ाइल सफलतापूर्वक अपडेट हुई!',
    profile_fullname: 'पूरा नाम',
    profile_email:    'ईमेल पता',
    profile_age:      'आयु',
    profile_gender:   'लिंग',
    profile_phone:    'फ़ोन',
    profile_readonly: 'केवल पढ़ें',
    profile_account:  'खाता',
    profile_chg_pwd:  'पासवर्ड बदलें',
    profile_chg_sub:  'अपना लॉगिन पासवर्ड अपडेट करें',
    profile_update:   'अपडेट',
    profile_del_acct: 'खाता हटाएं',
    profile_del_sub:  'अपना खाता और सभी डेटा स्थायी रूप से हटाएं',
    profile_delete:   'हटाएं',
    settings_title:   'सेटिंग्स',
    settings_sub:     'अपनी प्राथमिकताएं प्रबंधित करें',
    settings_appear:  'रूप',
    settings_appear_sub: 'ऐप कैसा दिखे यह चुनें',
    settings_lang:    'भाषा और क्षेत्र',
    settings_lang_sub:'अपनी पसंदीदा भाषा चुनें',
    settings_language:'भाषा',
    settings_timezone:'समय क्षेत्र',
    settings_save:    'बदलाव सहेजें',
    settings_saved:   'सहेजा गया!',
    settings_cur_theme:'वर्तमान थीम',
    settings_acct:    'खाता सेटिंग्स',
    settings_manage:  'प्रबंधित करें',
    theme_light:      'लाइट',
    theme_dark:       'डार्क',
    theme_neon:       'नियॉन',
    theme_light_desc: 'साफ सफेद इंटरफ़ेस',
    theme_dark_desc:  'आंखों के लिए आसान',
    theme_neon_desc:  'उच्च-कंट्रास्ट जीवंत',
    help_title:       'सहायता',
    help_sub:         'उत्तर खोजें या हमसे संपर्क करें',
    help_docs:        'दस्तावेज़ीकरण',
    help_docs_sub:    'गाइड और API डॉक्स',
    help_chat:        'लाइव चैट',
    help_chat_sub:    'सोम–शुक्र, 9am–6pm',
    help_email:       'ईमेल करें',
    help_faq:         'अक्सर पूछे जाने वाले प्रश्न',
    help_search:      'प्रश्न खोजें…',
    help_contact:     'संदेश भेजें',
    help_contact_sub: 'हम 1 कार्य दिवस में जवाब देंगे',
    help_send:        'संदेश भेजें',
    help_name:        'नाम',
    help_email_lbl:   'ईमेल',
    help_subject:     'विषय',
    help_message:     'संदेश',
    help_sent:        'संदेश भेजा गया!',
    about_leadership: 'नेतृत्व',
    about_team:       'हमारी टीम',
    about_papers:     'शोध पत्र',
    about_mission:    'हमारा मिशन',
    about_tech:       'हमारी तकनीक',
    about_open_pdf:   'PDF खोलें',
    logout_title:     'लॉग आउट करें?',
    logout_msg:       'आपको लॉगिन स्क्रीन पर वापस किया जाएगा।',
    logout_cancel:    'रद्द करें',
    logout_confirm:   'हाँ, लॉग आउट',
  },

  Telugu: {
    nav_dashboard:    'డాష్‌బోర్డ్',
    nav_upload:       'ECG చిత్రాన్ని అప్‌లోడ్ చేయండి',
    nav_settings:     'సెట్టింగ్‌లు',
    nav_about:        'మా గురించి',
    nav_support:      'సహాయం',
    nav_profile:      'నా ప్రొఫైల్',
    nav_logout:       'లాగ్ అవుట్',
    nav_new_scan:     '+ కొత్త ECG స్కాన్',
    nav_ecg_digitizer:'ECG డిజిటైజర్',
    dash_welcome:     'తిరిగి స్వాగతం',
    dash_summary:     'మీ ECG డిజిటైజేషన్ కార్యాచరణ సారాంశం',
    dash_total_scans: 'మొత్తం స్కాన్‌లు',
    dash_avg_snr:     'సగటు SNR',
    dash_avg_time:    'సగటు ప్రాసెసింగ్ సమయం',
    dash_avg_dice:    'సగటు Dice స్కోర్',
    dash_recent:      'ఇటీవలి స్కాన్‌లు',
    dash_new_scan:    '+ కొత్త స్కాన్',
    dash_record_id:   'రికార్డ్ ID',
    dash_date:        'తేదీ',
    dash_leads:       'లీడ్‌లు',
    dash_snr:         'SNR',
    dash_duration:    'వ్యవధి',
    dash_status:      'స్థితి',
    dash_success:     'విజయవంతం',
    dash_cta_title:   'కొత్త ECG విశ్లేషణకు సిద్ధంగా ఉన్నారా?',
    dash_cta_sub:     'పేపర్ స్కాన్ అప్‌లోడ్ చేయండి మరియు ఒక నిమిషంలో సిగ్నల్‌లు పొందండి',
    dash_cta_btn:     'విశ్లేషణ ప్రారంభించండి →',
    dash_no_scans:    'ఇంకా స్కాన్‌లు లేవు.',
    dash_upload_first:'మీ మొదటి ECG అప్‌లోడ్ చేయండి →',
    dash_refresh:     'రిఫ్రెష్',
    upload_title:     '12-లీడ్ ECG విశ్లేషకుడు',
    upload_sub:       'పేపర్ లేదా డిజిటల్ ECG అప్‌లోడ్ చేయండి',
    upload_select:    'ECG చిత్రాన్ని ఎంచుకోండి',
    upload_choose:    'ECG చిత్రాన్ని ఎంచుకోవడానికి క్లిక్ చేయండి…',
    upload_analyze:   'ECG విశ్లేషించండి',
    upload_processing:'ప్రాసెస్ అవుతోంది…',
    upload_error:     'సర్వర్ కనెక్షన్ విఫలమైంది',
    upload_empty_h:   'ఇంకా ECG విశ్లేషించబడలేదు',
    upload_empty_p:   'ప్రారంభించడానికి పైన ECG చిత్రాన్ని అప్‌లోడ్ చేయండి',
    upload_leads:     'గుర్తించిన లీడ్‌లు',
    upload_samples:   'నమూనాలు (లీడ్ II)',
    upload_duration:  'వ్యవధి (అంచనా)',
    upload_snr:       'SNR స్కోర్',
    upload_record:    'రికార్డ్ ID',
    tab_medical:      '📋 మెడికల్ ECG',
    tab_leads:        '📈 అన్ని లీడ్‌లు',
    tab_overlay:      '🔬 13-లీడ్ ఓవర్లే',
    tab_original:     '🖼 అసలు చిత్రం',
    profile_title:    'నా ప్రొఫైల్',
    profile_sub:      'మీ వ్యక్తిగత సమాచారాన్ని వీక్షించండి మరియు నిర్వహించండి',
    profile_edit:     'ప్రొఫైల్ సవరించు',
    profile_save:     'మార్పులు సేవ్ చేయండి',
    profile_cancel:   'రద్దు',
    profile_complete: 'ప్రొఫైల్ పూర్తయింది',
    profile_total:    'మొత్తం స్కాన్‌లు',
    profile_snr:      'సగటు SNR',
    profile_upload_photo: 'ఫోటో అప్‌లోడ్ చేయండి',
    profile_change_photo: 'ఫోటో మార్చండి',
    profile_remove:   'తొలగించు',
    profile_info:     'వ్యక్తిగత సమాచారం',
    profile_info_sub: 'మీ ప్రాథమిక ప్రొఫైల్ వివరాలు',
    profile_updated:  'ప్రొఫైల్ విజయవంతంగా అప్‌డేట్ అయింది!',
    profile_fullname: 'పూర్తి పేరు',
    profile_email:    'ఇమెయిల్ చిరునామా',
    profile_age:      'వయస్సు',
    profile_gender:   'లింగం',
    profile_phone:    'ఫోన్',
    profile_readonly: 'చదవడానికి మాత్రమే',
    profile_account:  'ఖాతా',
    profile_chg_pwd:  'పాస్‌వర్డ్ మార్చండి',
    profile_chg_sub:  'మీ లాగిన్ పాస్‌వర్డ్ అప్‌డేట్ చేయండి',
    profile_update:   'అప్‌డేట్',
    profile_del_acct: 'ఖాతా తొలగించు',
    profile_del_sub:  'మీ ఖాతా మరియు డేటాను శాశ్వతంగా తొలగించండి',
    profile_delete:   'తొలగించు',
    settings_title:   'సెట్టింగ్‌లు',
    settings_sub:     'మీ ప్రాధాన్యతలను నిర్వహించండి',
    settings_appear:  'రూపం',
    settings_appear_sub: 'యాప్ ఎలా కనిపించాలో ఎంచుకోండి',
    settings_lang:    'భాష మరియు ప్రాంతం',
    settings_lang_sub:'మీకు నచ్చిన భాషను ఎంచుకోండి',
    settings_language:'భాష',
    settings_timezone:'సమయ మండలం',
    settings_save:    'మార్పులు సేవ్ చేయండి',
    settings_saved:   'సేవ్ అయింది!',
    settings_cur_theme:'ప్రస్తుత థీమ్',
    settings_acct:    'ఖాతా సెట్టింగ్‌లు',
    settings_manage:  'నిర్వహించు',
    theme_light:      'లైట్',
    theme_dark:       'డార్క్',
    theme_neon:       'నియాన్',
    theme_light_desc: 'శుభ్రమైన తెల్లని ఇంటర్‌ఫేస్',
    theme_dark_desc:  'కళ్ళకు సులభం',
    theme_neon_desc:  'హై-కాంట్రాస్ట్ వైబ్రంట్',
    help_title:       'సహాయం మరియు మద్దతు',
    help_sub:         'సమాధానాలు కనుగొనండి లేదా మాతో సంప్రదించండి',
    help_docs:        'డాక్యుమెంటేషన్',
    help_docs_sub:    'గైడ్‌లు & API డాక్స్',
    help_chat:        'లైవ్ చాట్',
    help_chat_sub:    'సోమ–శుక్ర, 9am–6pm',
    help_email:       'ఇమెయిల్ పంపండి',
    help_faq:         'తరచుగా అడిగే ప్రశ్నలు',
    help_search:      'ప్రశ్నలు వెతకండి…',
    help_contact:     'సందేశం పంపండి',
    help_contact_sub: 'మేము 1 పని దినంలో జవాబు ఇస్తాము',
    help_send:        'సందేశం పంపండి',
    help_name:        'పేరు',
    help_email_lbl:   'ఇమెయిల్',
    help_subject:     'విషయం',
    help_message:     'సందేశం',
    help_sent:        'సందేశం పంపబడింది!',
    about_leadership: 'నాయకత్వం',
    about_team:       'మా బృందం',
    about_papers:     'పరిశోధనా పత్రాలు',
    about_mission:    'మా లక్ష్యం',
    about_tech:       'మా సాంకేతికత',
    about_open_pdf:   'PDF తెరవండి',
    logout_title:     'లాగ్ అవుట్ అవుతారా?',
    logout_msg:       'మీరు లాగిన్ స్క్రీన్‌కు తిరిగి వస్తారు.',
    logout_cancel:    'రద్దు',
    logout_confirm:   'అవును, లాగ్ అవుట్',
  },

  Tamil: {
    nav_dashboard:    'டாஷ்போர்டு',
    nav_upload:       'ECG படத்தை பதிவேற்று',
    nav_settings:     'அமைப்புகள்',
    nav_about:        'எங்களை பற்றி',
    nav_support:      'உதவி',
    nav_profile:      'என் சுயவிவரம்',
    nav_logout:       'வெளியேறு',
    nav_new_scan:     '+ புதிய ECG ஸ்கேன்',
    nav_ecg_digitizer:'ECG டிஜிட்டைசர்',
    dash_welcome:     'மீண்டும் வரவேற்கிறோம்',
    dash_summary:     'உங்கள் ECG டிஜிட்டைசேஷன் செயல்பாட்டின் சுருக்கம்',
    dash_total_scans: 'மொத்த ஸ்கேன்கள்',
    dash_avg_snr:     'சராசரி SNR',
    dash_avg_time:    'சராசரி செயலாக்க நேரம்',
    dash_avg_dice:    'சராசரி Dice மதிப்பெண்',
    dash_recent:      'சமீபத்திய ஸ்கேன்கள்',
    dash_new_scan:    '+ புதிய ஸ்கேன்',
    dash_record_id:   'பதிவு ID',
    dash_date:        'தேதி',
    dash_leads:       'லீடுகள்',
    dash_snr:         'SNR',
    dash_duration:    'கால அளவு',
    dash_status:      'நிலை',
    dash_success:     'வெற்றி',
    dash_cta_title:   'புதிய ECG பகுப்பாய்வுக்கு தயாரா?',
    dash_cta_sub:     'காகித ஸ்கேனை பதிவேற்றி ஒரு நிமிடத்தில் சிக்னல்கள் பெறுங்கள்',
    dash_cta_btn:     'பகுப்பாய்வு தொடங்கு →',
    dash_no_scans:    'இன்னும் ஸ்கேன்கள் இல்லை.',
    dash_upload_first:'உங்கள் முதல் ECG பதிவேற்றுங்கள் →',
    dash_refresh:     'புதுப்பி',
    upload_title:     '12-லீட் ECG பகுப்பாய்வி',
    upload_sub:       'காகித அல்லது டிஜிட்டல் ECG பதிவேற்றுங்கள்',
    upload_select:    'ECG படம் தேர்வு செய்யுங்கள்',
    upload_choose:    'ECG படம் தேர்வு செய்ய கிளிக் செய்யுங்கள்…',
    upload_analyze:   'ECG பகுப்பாய்வு செய்',
    upload_processing:'செயலாக்கப்படுகிறது…',
    upload_error:     'சர்வர் இணைப்பு தோல்வி',
    upload_empty_h:   'இன்னும் ECG பகுப்பாய்வு செய்யப்படவில்லை',
    upload_empty_p:   'தொடங்க மேலே ECG படத்தை பதிவேற்றுங்கள்',
    upload_leads:     'கண்டறியப்பட்ட லீடுகள்',
    upload_samples:   'மாதிரிகள் (லீட் II)',
    upload_duration:  'கால அளவு (மதிப்பீடு)',
    upload_snr:       'SNR மதிப்பெண்',
    upload_record:    'பதிவு ID',
    tab_medical:      '📋 மருத்துவ ECG',
    tab_leads:        '📈 அனைத்து லீடுகள்',
    tab_overlay:      '🔬 13-லீட் மேலடுக்கு',
    tab_original:     '🖼 அசல் படம்',
    profile_title:    'என் சுயவிவரம்',
    profile_sub:      'உங்கள் தனிப்பட்ட தகவலை பார்க்கவும் நிர்வகிக்கவும்',
    profile_edit:     'சுயவிவரம் திருத்து',
    profile_save:     'மாற்றங்களை சேமி',
    profile_cancel:   'ரத்து செய்',
    profile_complete: 'சுயவிவரம் பூர்த்தி',
    profile_total:    'மொத்த ஸ்கேன்கள்',
    profile_snr:      'சராசரி SNR',
    profile_upload_photo: 'புகைப்படம் பதிவேற்று',
    profile_change_photo: 'புகைப்படம் மாற்று',
    profile_remove:   'அகற்று',
    profile_info:     'தனிப்பட்ட தகவல்',
    profile_info_sub: 'உங்கள் அடிப்படை சுயவிவர விவரங்கள்',
    profile_updated:  'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    profile_fullname: 'முழு பெயர்',
    profile_email:    'மின்னஞ்சல் முகவரி',
    profile_age:      'வயது',
    profile_gender:   'பாலினம்',
    profile_phone:    'தொலைபேசி',
    profile_readonly: 'படிக்க மட்டும்',
    profile_account:  'கணக்கு',
    profile_chg_pwd:  'கடவுச்சொல் மாற்று',
    profile_chg_sub:  'உங்கள் உள்நுழைவு கடவுச்சொல்லை புதுப்பிக்கவும்',
    profile_update:   'புதுப்பி',
    profile_del_acct: 'கணக்கை நீக்கு',
    profile_del_sub:  'உங்கள் கணக்கு மற்றும் எல்லா தரவையும் நிரந்தரமாக நீக்கவும்',
    profile_delete:   'நீக்கு',
    settings_title:   'அமைப்புகள்',
    settings_sub:     'உங்கள் விருப்பங்களை நிர்வகிக்கவும்',
    settings_appear:  'தோற்றம்',
    settings_appear_sub: 'செயலி எப்படி தெரிய வேண்டும் என்று தேர்வு செய்யுங்கள்',
    settings_lang:    'மொழி மற்றும் பிராந்தியம்',
    settings_lang_sub:'உங்கள் விருப்பமான மொழியை தேர்வு செய்யுங்கள்',
    settings_language:'மொழி',
    settings_timezone:'நேர மண்டலம்',
    settings_save:    'மாற்றங்களை சேமி',
    settings_saved:   'சேமிக்கப்பட்டது!',
    settings_cur_theme:'தற்போதைய தீம்',
    settings_acct:    'கணக்கு அமைப்புகள்',
    settings_manage:  'நிர்வகி',
    theme_light:      'லைட்',
    theme_dark:       'டார்க்',
    theme_neon:       'நியான்',
    theme_light_desc: 'சுத்தமான வெள்ளை இடைமுகம்',
    theme_dark_desc:  'கண்களுக்கு எளிது',
    theme_neon_desc:  'உயர்-மாறுபாடு துடிப்பான',
    help_title:       'உதவி மற்றும் ஆதரவு',
    help_sub:         'பதில்கள் தேடுங்கள் அல்லது எங்களை தொடர்பு கொள்ளுங்கள்',
    help_docs:        'ஆவணங்கள்',
    help_docs_sub:    'வழிகாட்டிகள் & API ஆவணங்கள்',
    help_chat:        'நேரடி அரட்டை',
    help_chat_sub:    'திங்கள்–வெள்ளி, காலை 9–மாலை 6',
    help_email:       'மின்னஞ்சல் அனுப்பு',
    help_faq:         'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    help_search:      'கேள்விகளை தேடு…',
    help_contact:     'செய்தி அனுப்பு',
    help_contact_sub: '1 வேலை நாளில் பதில் அளிப்போம்',
    help_send:        'செய்தி அனுப்பு',
    help_name:        'பெயர்',
    help_email_lbl:   'மின்னஞ்சல்',
    help_subject:     'பொருள்',
    help_message:     'செய்தி',
    help_sent:        'செய்தி அனுப்பப்பட்டது!',
    about_leadership: 'தலைமை',
    about_team:       'எங்கள் குழு',
    about_papers:     'ஆராய்ச்சி கட்டுரைகள்',
    about_mission:    'எங்கள் நோக்கம்',
    about_tech:       'எங்கள் தொழில்நுட்பம்',
    about_open_pdf:   'PDF திற',
    logout_title:     'வெளியேற விரும்புகிறீர்களா?',
    logout_msg:       'உங்களை உள்நுழைவு திரைக்கு திருப்பி அனுப்புவோம்.',
    logout_cancel:    'ரத்து',
    logout_confirm:   'ஆம், வெளியேறு',
  },

  Kannada: {
    nav_dashboard:    'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    nav_upload:       'ECG ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    nav_settings:     'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    nav_about:        'ನಮ್ಮ ಬಗ್ಗೆ',
    nav_support:      'ಸಹಾಯ',
    nav_profile:      'ನನ್ನ ಪ್ರೊಫೈಲ್',
    nav_logout:       'ಲಾಗ್ ಔಟ್',
    nav_new_scan:     '+ ಹೊಸ ECG ಸ್ಕ್ಯಾನ್',
    nav_ecg_digitizer:'ECG ಡಿಜಿಟೈಜರ್',
    dash_welcome:     'ಮತ್ತೆ ಸ್ವಾಗತ',
    dash_summary:     'ನಿಮ್ಮ ECG ಡಿಜಿಟೈಸೇಶನ್ ಚಟುವಟಿಕೆಯ ಸಾರಾಂಶ',
    dash_total_scans: 'ಒಟ್ಟು ಸ್ಕ್ಯಾನ್‌ಗಳು',
    dash_avg_snr:     'ಸರಾಸರಿ SNR',
    dash_avg_time:    'ಸರಾಸರಿ ಪ್ರಕ್ರಿಯೆ ಸಮಯ',
    dash_avg_dice:    'ಸರಾಸರಿ Dice ಸ್ಕೋರ್',
    dash_recent:      'ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್‌ಗಳು',
    dash_new_scan:    '+ ಹೊಸ ಸ್ಕ್ಯಾನ್',
    dash_record_id:   'ರೆಕಾರ್ಡ್ ID',
    dash_date:        'ದಿನಾಂಕ',
    dash_leads:       'ಲೀಡ್‌ಗಳು',
    dash_snr:         'SNR',
    dash_duration:    'ಅವಧಿ',
    dash_status:      'ಸ್ಥಿತಿ',
    dash_success:     'ಯಶಸ್ವಿ',
    dash_cta_title:   'ಹೊಸ ECG ವಿಶ್ಲೇಷಣೆಗೆ ಸಿದ್ಧರಿದ್ದೀರಾ?',
    dash_cta_sub:     'ಪೇಪರ್ ಸ್ಕ್ಯಾನ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಒಂದು ನಿಮಿಷದಲ್ಲಿ ಸಿಗ್ನಲ್‌ಗಳು ಪಡೆಯಿರಿ',
    dash_cta_btn:     'ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಿ →',
    dash_no_scans:    'ಇನ್ನೂ ಸ್ಕ್ಯಾನ್‌ಗಳಿಲ್ಲ.',
    dash_upload_first:'ನಿಮ್ಮ ಮೊದಲ ECG ಅಪ್‌ಲೋಡ್ ಮಾಡಿ →',
    dash_refresh:     'ರಿಫ್ರೆಶ್',
    upload_title:     '12-ಲೀಡ್ ECG ವಿಶ್ಲೇಷಕ',
    upload_sub:       'ಪೇಪರ್ ಅಥವಾ ಡಿಜಿಟಲ್ ECG ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    upload_select:    'ECG ಚಿತ್ರ ಆಯ್ಕೆ ಮಾಡಿ',
    upload_choose:    'ECG ಚಿತ್ರ ಆಯ್ಕೆ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ…',
    upload_analyze:   'ECG ವಿಶ್ಲೇಷಿಸಿ',
    upload_processing:'ಪ್ರಕ್ರಿಯೆ ಮಾಡಲಾಗುತ್ತಿದೆ…',
    upload_error:     'ಸರ್ವರ್ ಸಂಪರ್ಕ ವಿಫಲವಾಗಿದೆ',
    upload_empty_h:   'ಇನ್ನೂ ECG ವಿಶ್ಲೇಷಿಸಲಾಗಿಲ್ಲ',
    upload_empty_p:   'ಪ್ರಾರಂಭಿಸಲು ಮೇಲೆ ECG ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    upload_leads:     'ಪತ್ತೆಹಚ್ಚಿದ ಲೀಡ್‌ಗಳು',
    upload_samples:   'ಮಾದರಿಗಳು (ಲೀಡ್ II)',
    upload_duration:  'ಅವಧಿ (ಅಂದಾಜು)',
    upload_snr:       'SNR ಸ್ಕೋರ್',
    upload_record:    'ರೆಕಾರ್ಡ್ ID',
    tab_medical:      '📋 ವೈದ್ಯಕೀಯ ECG',
    tab_leads:        '📈 ಎಲ್ಲ ಲೀಡ್‌ಗಳು',
    tab_overlay:      '🔬 13-ಲೀಡ್ ಓವರ್ಲೇ',
    tab_original:     '🖼 ಮೂಲ ಚಿತ್ರ',
    profile_title:    'ನನ್ನ ಪ್ರೊಫೈಲ್',
    profile_sub:      'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ ವೀಕ್ಷಿಸಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ',
    profile_edit:     'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    profile_save:     'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    profile_cancel:   'ರದ್ದು ಮಾಡಿ',
    profile_complete: 'ಪ್ರೊಫೈಲ್ ಪೂರ್ಣ',
    profile_total:    'ಒಟ್ಟು ಸ್ಕ್ಯಾನ್‌ಗಳು',
    profile_snr:      'ಸರಾಸರಿ SNR',
    profile_upload_photo: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    profile_change_photo: 'ಫೋಟೋ ಬದಲಾಯಿಸಿ',
    profile_remove:   'ತೆಗೆದುಹಾಕಿ',
    profile_info:     'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ',
    profile_info_sub: 'ನಿಮ್ಮ ಮೂಲ ಪ್ರೊಫೈಲ್ ವಿವರಗಳು',
    profile_updated:  'ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',
    profile_fullname: 'ಪೂರ್ಣ ಹೆಸರು',
    profile_email:    'ಇಮೇಲ್ ವಿಳಾಸ',
    profile_age:      'ವಯಸ್ಸು',
    profile_gender:   'ಲಿಂಗ',
    profile_phone:    'ಫೋನ್',
    profile_readonly: 'ಓದಲು ಮಾತ್ರ',
    profile_account:  'ಖಾತೆ',
    profile_chg_pwd:  'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
    profile_chg_sub:  'ನಿಮ್ಮ ಲಾಗಿನ್ ಪಾಸ್‌ವರ್ಡ್ ನವೀಕರಿಸಿ',
    profile_update:   'ನವೀಕರಿಸಿ',
    profile_del_acct: 'ಖಾತೆ ಅಳಿಸಿ',
    profile_del_sub:  'ನಿಮ್ಮ ಖಾತೆ ಮತ್ತು ಎಲ್ಲ ಡೇಟಾ ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಿ',
    profile_delete:   'ಅಳಿಸಿ',
    settings_title:   'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    settings_sub:     'ನಿಮ್ಮ ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    settings_appear:  'ನೋಟ',
    settings_appear_sub: 'ಅಪ್ಲಿಕೇಶನ್ ಹೇಗೆ ಕಾಣಬೇಕು ಎಂದು ಆಯ್ಕೆ ಮಾಡಿ',
    settings_lang:    'ಭಾಷೆ ಮತ್ತು ಪ್ರದೇಶ',
    settings_lang_sub:'ನಿಮ್ಮ ಇಷ್ಟದ ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
    settings_language:'ಭಾಷೆ',
    settings_timezone:'ಸಮಯ ವಲಯ',
    settings_save:    'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    settings_saved:   'ಉಳಿಸಲಾಗಿದೆ!',
    settings_cur_theme:'ಪ್ರಸ್ತುತ ಥೀಮ್',
    settings_acct:    'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    settings_manage:  'ನಿರ್ವಹಿಸಿ',
    theme_light:      'ಲೈಟ್',
    theme_dark:       'ಡಾರ್ಕ್',
    theme_neon:       'ನಿಯಾನ್',
    theme_light_desc: 'ಸ್ವಚ್ಛ ಬಿಳಿ ಇಂಟರ್‌ಫೇಸ್',
    theme_dark_desc:  'ಕಣ್ಣುಗಳಿಗೆ ಸುಲಭ',
    theme_neon_desc:  'ಹೈ-ಕಾಂಟ್ರಾಸ್ಟ್ ವೈಬ್ರಂಟ್',
    help_title:       'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    help_sub:         'ಉತ್ತರಗಳನ್ನು ಹುಡುಕಿ ಅಥವಾ ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    help_docs:        'ದಾಖಲೆಗಳು',
    help_docs_sub:    'ಮಾರ್ಗದರ್ಶಿಗಳು & API ಡಾಕ್ಸ್',
    help_chat:        'ನೇರ ಚಾಟ್',
    help_chat_sub:    'ಸೋಮ–ಶುಕ್ರ, 9am–6pm',
    help_email:       'ಇಮೇಲ್ ಮಾಡಿ',
    help_faq:         'ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು',
    help_search:      'ಪ್ರಶ್ನೆಗಳನ್ನು ಹುಡುಕಿ…',
    help_contact:     'ಸಂದೇಶ ಕಳುಹಿಸಿ',
    help_contact_sub: '1 ಕೆಲಸದ ದಿನದಲ್ಲಿ ಪ್ರತಿಕ್ರಿಯಿಸುತ್ತೇವೆ',
    help_send:        'ಸಂದೇಶ ಕಳುಹಿಸಿ',
    help_name:        'ಹೆಸರು',
    help_email_lbl:   'ಇಮೇಲ್',
    help_subject:     'ವಿಷಯ',
    help_message:     'ಸಂದೇಶ',
    help_sent:        'ಸಂದೇಶ ಕಳುಹಿಸಲಾಗಿದೆ!',
    about_leadership: 'ನಾಯಕತ್ವ',
    about_team:       'ನಮ್ಮ ತಂಡ',
    about_papers:     'ಸಂಶೋಧನಾ ಪ್ರಬಂಧಗಳು',
    about_mission:    'ನಮ್ಮ ಧ್ಯೇಯ',
    about_tech:       'ನಮ್ಮ ತಂತ್ರಜ್ಞಾನ',
    about_open_pdf:   'PDF ತೆರೆಯಿರಿ',
    logout_title:     'ಲಾಗ್ ಔಟ್ ಮಾಡುವಿರಾ?',
    logout_msg:       'ನಿಮ್ಮನ್ನು ಲಾಗಿನ್ ಪರದೆಗೆ ಹಿಂದಿರುಗಿಸಲಾಗುತ್ತದೆ.',
    logout_cancel:    'ರದ್ದು',
    logout_confirm:   'ಹೌದು, ಲಾಗ್ ಔಟ್',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem('ecg-language') || 'English'
  );

  const t = (key) => TRANSLATIONS[language]?.[key] ?? TRANSLATIONS['English'][key] ?? key;

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('ecg-language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}